### ISSUE TITLE
This sample works but not because of linkerd or istio, but kubernetes its self.

### ISSUE THREAD

**Issue by FrostyLeaf** [scholzj/vertx-grpc-echo#1]
https://github.com/scholzj/vertx-grpc-echo/blob/master/kubernetes/client.yaml#L25~L28
It works even without linkerd or istio. Caz <svc-name><namespace>.svc.cluster.local:<port> is routed through a TCP L4 lb, which is provided by Kubernetes, for Service resource.

**Comment by scholzj** [comment]
To be honest, it is a long time since I used these for blog post and for  _studying_ purposes. I'm not sure they still work properly. The examples directly in `/kubernetes/` use the Kubernetes service. The Kubernetes service is only a L4 load balancer and basically load balances only TCP connections. Where as Istio and Linkerd work on L7 and are able to balance specific GRPC requests. Because GRPC is using long lived connections, it should have following impact: 

With the Kubernetes service it will work, but client opens the connection, the k8s service routes it to one server pod and all requests send over this connection go to this single server pod. That can mean that with one client instance you will always use only one server instance. That might not be such a big deal because there might be many client instances which will each connect to single server, but each to different one. However often it would happen that one client instances would produce significantly more traffic than the others. And this traffic will be routed to single server pod. With Linkerd or Istio you will loadbalance not just TCP connections but actual requests. So the load will be distributed more evenly.

**Comment by FrostyLeaf** [comment]
You mean, when neither the Linkerd nor Istio is installed, this example works with a L4 lb. Otherwise, this exactly same example, it works with a L7 lb which is provided by Linkerd or Istio?

**Comment by scholzj** [comment]
Istio is using sidecar container with Envoy proxy which basically hijacks all the traffic from your pod and routes the traffic through the Istio mesh. You are still connecting using the service name - but Istio is using it only for service discovery. It takes the Kubernetes service, finds the endpoints for this service (the pods which are serving) but sends the traffic to them on its own not through the service. So in that case the basic YAML of the client and server stays the same but it needs to be injected the Istio sidecar. TBH I haven't looked much at Istio since more than - but I think this principle is still the same. At the time I was doing this you had to use the command `istioctl kube-inject -f client.yaml` to modify the YMAL and inject the proxy.

Linkerd works differently (or worked at that time). You deployed it as a daemon set and connected to the Linkerd running on your Kubernetes node. And you have to configure Linkerd to understand where do you want to send and receive the data. You can see this in the subdirectory `kubernetes/linkerd/`

**Comment by scholzj** [comment]
I realised the blog post is not linked anywhere here and I'm not sure you have seen it - it might explain some of the stuff: [https://blog.effectivemessaging.com/2017/06/load-balancing-grpc-connections-in.html](https://blog.effectivemessaging.com/2017/06/load-balancing-grpc-connections-in.html)

**Comment by FrostyLeaf** [comment]
Yeah, I have read it. I'll read it again. I think maybe I have lost something.

**Comment by FrostyLeaf** [comment]
You're right. When Istio installed and istio-proxy injected, the Services works behind Envoy. I misunderstood the mechanism. Thanks for your help.

**Comment by scholzj** [comment]
No problem ... I'm glad this helped!
